version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: "01:00"
      timezone: Europe/Moscow
    open-pull-requests-limit: 99
    assignees:
    - MikeVL
